### PR TITLE
Exclude web-app folder from plugin

### PR DESCRIPTION
**Pull request by kevana**
Ran into some issues with assets with the jaxrs plugin overriding assets from other plugins.

### CODE REVIEW

**Comment by kevana** [comment]
Bump

**Comment by ctoestreich** [comment]
@krasserm Are you still maintaining this plugin?

**Comment by krasserm** [comment]
@ctoestreich I'm sorry to say that I don't have time any more to maintain this plugin. Recently, @noamt and @davidecavestro did a great job further developing it but I don't know their current status either.

**Comment by noamt** [comment]
Sorry for the delay; time is so scarce

**Pull request merged**
